### ISSUE TITLE
Retos Sesión 01 y Retos Sesión 02

### ISSUE THREAD

**Issue by jevillanueva** [andres-guzman/psg-example#1]
Algunas correcciones por ahora :D
https://github.com/andres-guzman/psg-example/blob/main/ejercicio_01.md
https://github.com/andres-guzman/psg-example/blob/main/ejercicio_02.md

Tienen que estar en una carpeta llamada: *retos_sesion_02*

Aqui esta las instrucciones: https://study.pylapaz.org/content/sesion02/#/62

Tambien faltan los retos de la sesion 01: https://study.pylapaz.org/content/sesion01/#/82

**Comment by andres-guzman** [comment]
Ya adicioné los ejercicios e hice algunas correcciones de nombre de folders y archivos. :)

**Comment by jevillanueva** [comment]
Gran trabajo, sigue adelante!! :D
