### ISSUE TITLE
Retos Python Study Group 

### ISSUE THREAD

**Issue by jevillanueva** [andres-guzman/psg-example#2]
Hola de nuevo!

Veo que aun faltan retos del python study group....  
Me gustaria invitarte a que continues 😄 
Aquí encontrarás todas las sesiones y sus retos  https://study.pylapaz.org/
No te desanimes!! estare atento a tus retos, animo!!! 

--- 
Feedback:
4. Los retos de la sesion04 estan incompletos
Faltan los retos de la sesión 5 y 6
7.5. La solucion esta relacionada con el slice invertido, quitar espacios y todo en upper o lower para el palindromo
7.7. falta el notebook
8.1. Dice ingresar por teclado 3 veces y despues con las 3 variables armar la tupla
8.6. La formula que puedes usar es la siguiente: http://pspc1.weebly.com/uploads/2/4/5/4/24543920/9546976_orig.png
No te desanimes sigue adelante vas muy bien!!!

> El éxito es la suma de pequeños esfuerzos repetidos día tras día. - Robert Collier

**Comment by andres-guzman** [comment]
Ya he concluido con todos los ejercicios del Python Study Group La Paz :)
